name       : libdatrie
version    : 0.2.12
release    : 1
source     :
    - https://linux.thai.net/pub/thailinux/software/libthai/libdatrie-0.2.12.tar.xz : 452dcc4d3a96c01f80f7c291b42be11863cd1554ff78b93e110becce6e00b149
license    : LGPL-2.1-only
component  : desktop.library
summary    : Double-Array Trie Library
description: |
    An implementation of double-array structure for representing trie, as proposed by Junichi Aoe.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install -j1
